spring.application.name=prooflane-backend
server.port=8080

# Database Configuration (reads from environment variable)
spring.data.mongodb.uri=${MONGO_URI:mongodb://localhost:27017/prooflane_db}
spring.data.mongodb.auto-index-creation=true

# Actuator Health
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
